apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: n8n-project
  source:
    repoURL: https://github.com/Programmer-Network/k3s-n8n
    targetRevision: HEAD
    path: n8n-app
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
