# n8n deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  # Single replica as n8n is not designed for horizontal scaling
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      # Disable Kubernetes service environment variables to prevent conflicts
      enableServiceLinks: false
      # Set filesystem permissions for the n8n user (uid 1000)
      securityContext:
        fsGroup: 1000
      # Persistent storage for n8n data (workflows, credentials, etc.)
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
      containers:
        - name: n8n
          image: n8nio/n8n:1.98.1
          ports:
            - containerPort: 5678
          # Mount the persistent volume for n8n data
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          # Load configuration from ConfigMap and non-database secrets
          envFrom:
            - configMapRef:
                name: n8n-config
            - secretRef:
                name: n8n-secret
          # Health checks with generous initial delay for database connectivity
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /healthz
              port: 5678
            failureThreshold: 30
            periodSeconds: 10
          # Resource limits to prevent container from consuming too much memory
          resources:
            limits:
              cpu: "1.0"
              memory: "2048Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          # Environment variables for n8n configuration
          env:
            - name: N8N_HOST
              value: n8n.programmer.network
            - name: WEBHOOK_TUNNEL_URL
              value: http://n8n.programmer.network/
            # Database credentials from CloudNativePG-generated secret
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-pg-cluster-app
                  key: username
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-pg-cluster-app
                  key: password
