apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 1000
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
      containers:
        - name: n8n
          image: n8nio/n8n:1.98.1
          ports:
            - containerPort: 5678
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          envFrom:
            - configMapRef:
                name: n8n-config
            - secretRef:
                name: n8n-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5678
            initialDelaySeconds: 30
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /healthz
              port: 5678
            failureThreshold: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: "1.0"
              memory: "2048Mi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          env:
            - name: N8N_HOST
              value: n8n.programmer.network
            - name: WEBHOOK_TUNNEL_URL
              value: http://n8n.programmer.network/
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-pg-secret
                  key: password
