apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  DB_POSTGRESDB_PASSWORD: BASE64_PASSWORD
  N8N_BASIC_AUTH_PASSWORD: BASE64_PASSWORD
  N8N_ENCRYPTION_KEY: BASE64_KEY
