apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  DB_TYPE: postgres
  DB_POSTGRESDB_HOST: n8n-pg-cluster-rw
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_USER: n8n
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_HOST: n8n.programmer.network
  WEBHOOK_TUNNEL_URL: http://n8n.programmer.network/
