apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  DB_POSTGRESDB_PASSWORD: cGFzc3dvcmRfY2hhbmdlX21l # base64 for 'password_change_me'
  N8N_BASIC_AUTH_PASSWORD: cGFzc3dvcmRfY2hhbmdlX21l # base64 for 'password_change_me'
  N8N_ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfY2hhbmdlX21l # base64 for 'encryption_key_change_me'


encryption_key_change_me